# wallust v3 config for ida dotfiles
# This file is meant to be symlinked to ~/.config/wallust/wallust.toml

backend = "fastresize"
color_space = "lab"
palette = "dark"
saturation = 40

[templates]
# Generate theme artifacts into ~/.cache/ida-theme/current/
ida = { template = 'ida/', target = '~/.cache/ida-theme/current/', max_depth = 5 }
